package nl.rijksoverheid.minienw.travelvalidation.api.data.initialize

import com.fasterxml.jackson.annotation.JsonProperty
import com.google.gson.annotations.SerializedName

/**
* 3.10.2.2.3 Request Body
* The request body is a JSON structure which defines the user generated pubkey, the used key type and the subject.
 * NB Subject dropped as it is in the Airline Traveller/Trip Token.
*/
class ValidationInitializeRequestBody
    (
    /**
     * TODO why is this not a JWK so that the algorithm is specified?
    * ECDSA or RSA-PSS Key String var Key generated by the user/wallet(x.509 PEM)
    */
    @JsonProperty("pubKey")
    @SerializedName("pubKey")
    var walletPublicKey : String?,

    /**
    * ES256/PS256/RS256 String - Use Crypto Method according to JWT definitions in RFC75182 callback e.g.https://... String Optional Callback URL
     * */
    @JsonProperty("alg")
    @SerializedName("alg")
    var walletPublicKeyAlgorithm : String?,

    /**
    * Random 16 bytes, Base64 encoded
    */
    @JsonProperty("nonce")
    @SerializedName("nonce")
    var nonce : String?,
)

