package nl.rijksoverheid.minienw.travelvalidation.api.data.initialize

import com.fasterxml.jackson.annotation.JsonProperty
import com.google.gson.annotations.SerializedName
import io.swagger.annotations.ApiModelProperty

/**
* 3.10.2.2.3 Request Body
* The request body is a JSON structure which defines the user generated pubkey, the used key type and the subject.
 * NB Subject dropped as it is in the Airline Traveller/Trip Token.
*/
class ValidationInitializeRequestBody
    (
    /**
    * ECDSA
    */
    @JsonProperty("pubKey")
    @SerializedName("pubKey")
    @ApiModelProperty(required = true, notes="For calculating the digest of the encrypted DCC artifact - ECDSA public key generated by the wallet in ASN1->DER->BASE64 format.")
    var walletPublicKey : String?,

    /**
    * ECDsaWithSha256
     * */
    @JsonProperty("alg")
    @SerializedName("alg")
    @ApiModelProperty(required = true, notes="For calculating the digest of the encrypted DCC artifact - always use ECDsaWithSha256.")
    var walletPublicKeyAlgorithm : String?,

    /**
    * Random 16 bytes, Base64 encoded
    */
    @JsonProperty("nonce")
    @SerializedName("nonce")
    @ApiModelProperty(required = false, notes="Securely generated byte array of length 16. Used as the IV when using AES to encrypt the DCC artefact.")
    var nonce : String?,
)

